import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <nav className="flex px-10 py-5 items-center w-full">
          <ul className="flex space-x-2">
            <li>
              <Link href={"/subjects"}>Subjects</Link>
            </li>
            <li>
              <Link href={"/decks"}>Decks</Link>
            </li>
            <li>
              <Link href={"/cards"}>Cards</Link>
            </li>
            <li>
              <Link href={"/answers"}>Answers</Link>
            </li>
            <li>
              <Link href={"/session"}>Session</Link>
            </li>
          </ul>
        </nav>
        <div className="flex flex-col p-10">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
