import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/toaster";
import prisma from "@/lib/prisma";
import { BasicTree } from "./TreeView";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const data = [
  { id: "1", name: "Unread" },
  { id: "2", name: "Threads" },
  {
    id: "3",
    name: "Chat Rooms",
    children: [
      { id: "c1", name: "General" },
      { id: "c2", name: "Random" },
      { id: "c3", name: "Open Source Projects" },
    ],
  },
  {
    id: "4",
    name: "Direct Messages",
    children: [
      { id: "d1", name: "Alice" },
      { id: "d2", name: "Bob" },
      { id: "d3", name: "Charlie" },
    ],
  },
];

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const tree = await prisma.subject.findMany({ include: { children: true } });

  console.log(tree.map((node) => node.children));

  return (
    <html className="dark" lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <nav className="flex px-10 py-5 items-center w-full">
          <ul className="flex space-x-2">
            <li>
              <Link href={"/"}>Dashboard</Link>
            </li>

            <li>
              <Link href={"/subjects"}>Subjects</Link>
            </li>
            <li>
              <Link href={"/decks"}>Decks</Link>
            </li>
            <li>
              <Link href={"/cards"}>Cards</Link>
            </li>
            <li>
              <Link href={"/answers"}>Answers</Link>
            </li>
          </ul>
        </nav>
        <div className="flex">
          <div className="flex flex-col">
            <BasicTree data={tree} />
          </div>
          <div className="w-full">{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
