import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import { PropsWithChildren } from "react";
import { NavBar } from "./NavBar";

export const dynamic = "force-dynamic";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <html className="dark" lang="en">
      <body
        className={cn("bg-background font-sans antialiased", fontSans.variable)}
      >
        <NavBar />
        <main className="min-h-[calc(100vh_-_80px)]">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
