import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Resources, client } from "@/lib/dotnetApi";
import AuthProvider from "@/providers/AuthProvider";

export const dynamic = "force-dynamic";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const tree = (await client.getResources({ resource: Resources.Tree })) as [];

  return (
    <AuthProvider>
      <html className="dark" lang="en">
        <body
          className={cn(
            "max-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          {children}
          <Toaster />
        </body>
      </html>
    </AuthProvider>
  );
}
